### ISSUE TITLE
Question - Best Practice to use this Plugin on a multilingual website

### ISSUE THREAD

**Issue by dannystarkDE** [am-impact/amnav#101]
What is the right way to use this plugin on a multilingual website?
Do I have to create a separate menu for each language?

If I currently switch to another language, the navigation disappears.
What could I do wrong?

**Comment by hubertprein** [comment]
You have to create a menu per language, yes. However, when you have created a menu, let's say "Main menu" and you edit that one; you will edit it in the primary locale. On the top right side, you can choose a different locale. So your menu stays intact, but you pick your nodes per locale.

**Comment by dannystarkDE** [comment]
Ahh okay. I hadn't noticed the dropdown menu.
Thank you very much!
