### ISSUE TITLE
Settings: maxLevel only used for drag and drop

### ISSUE THREAD

**Issue by nweevers** [am-impact/amnav#14]
You still can add items deeper then max Level with option 'parent page'

**Comment by joshangell** [comment]
Any update on when this might be fixed? Happy to sort out a PR just want to make sure no one has already done it.

**Comment by hubertprein** [comment]
@joshangell This has been fixed in the latest release that just got out. See commit: ddc9378faf7c6f6c9711896e1fff1401efbf0146

**Comment by joshangell** [comment]
Ah, sorry about that - should've checked first :flushed:

**Comment by hubertprein** [comment]
No worries. You couldn't know that, because I just released it a few minutes ago. :wink:
