### ISSUE TITLE
Wrong Url in Navigation and no "active" state

### ISSUE THREAD

**Issue by phaetons** [am-impact/amnav#19]
Tried your Plugin and like it alot, but i get two errors in the output:
1 - The URLs in the navigation includes the domain name twice, e.g.:
```
<a title="Impressum" href="http://www.domain.com/http://www.domain.com/index.php?p=impressum">Impressum</a>
```
This happens using craft.amNav.getNav() and craft.amNav.getNavRaw()

2 - The class "active" is not set, maybe it's because the url ist not correct.

**Comment by hubertprein** [comment]
1) Something must be wrong when you insert that node. Did you add it manually? Any specific details you could give on how you added this node to the navigation would be really helpful.

2) This is indeed because of the wrong URL.

**Comment by phaetons** [comment]
Hmm, 
i just added the single sections to the navigation via your plugin:
![craft_amnav](https://cloud.githubusercontent.com/assets/7963541/6244704/26465526-b757-11e4-9f6c-b115d9911398.jpg)

That's my code in the template:
```
{{ craft.amNav.getNav("footerMenue", {class:'footer-links'}) }}
```
And thats the output of the standard url output
siteUrl: http://test.craft.dev/
entry.url: http://test.craft.dev/index.php?p=impressum

**Comment by phaetons** [comment]
Can you give me a hint, where (in the plugin services?) the urls are created, so i can check the code?

**Comment by hubertprein** [comment]
I've been trying to recreate your situation on my end, but had no luck so far. I noticed that your URLs have the page within the URL (index.php in this case), so you're not using the search engine friendly URLs by using rewrite rules from the .htaccess file. Is there a reason you're working like this?

**Comment by phaetons** [comment]
I use the .htacces that comes with craft, mor_rewrite works, but i had to add 'omitScriptNameInUrls' => true in the config. I cleared the cache but still the same.

So i looked in the database.craft_amnav_pages and field "url" = {siteUrl}http://www.domain.de/index.php?p=impressum

**Comment by phaetons** [comment]
After adding 'omitScriptNameInUrls' => true in the config and adding a new site to the navigation the field "url" = {siteUrl}http://www.domain.de/team/arnd-rieten

**Comment by hubertprein** [comment]
Craft caches the part where you change the 'omitScriptNameInUrls' value. Is it possible you can send me a backup of your database, so I can have a quick look to figure out what's going wrong on your end?

**Comment by phaetons** [comment]
Yes, how can i send you backup?

**Comment by hubertprein** [comment]
Leave me your e-mail address and I'll contact you.

**Comment by phaetons** [comment]
Ok, here is my mail: phaetons@gmx.de

**Comment by pixeljitsu** [comment]
Having this same issue.  Is there a way to resolve it?

Thanks :)

**Comment by joshangell** [comment]
+1 - me too

**Comment by hubertprein** [comment]
Hmm that's weird.. 

@pixeljitsu , @joshangell Do you have the script name in the URL as @phaetons ? AmNav changes {siteUrl} to your siteUrl in Craft CP or if overridden from general.php.

In our projects, we change our siteUrl based on the current platform (development, live, etc..). Just by adding the siteUrl to the array in general.php. We add the locale(s) to the array we need and it runs without any problems. Like this: http://cl.ly/image/053a1S3b1X0q
Could one of you try this?

**Comment by phaetons** [comment]
Ok, adding 'siteUrl' to general.php works fine.

'url' in craft_amnav_pages without that:
```
{siteUrl}http://mydomain.de/team/joshua
```
'url' in craft_amnav_pages after adding 'siteUrl':
```
{siteUrl}team/joshua
```

Thank you and best regards

**Comment by hubertprein** [comment]
@phaetons That's good news. I'm glad it worked out.

**Comment by joshangell** [comment]
@hubertprein Excellent - that worked for me too, thanks! I was actually defining the `CRAFT_SITE_URL` constant already there, so I just set the `siteUrl` in the array as well.

**Comment by pixeljitsu** [comment]
I have it configured like this:
```
return array(
  '*' => array(
    'cpTrigger' => 'secret',
    'devMode' => false,
    'omitScriptNameInUrls' => true,
  ),
  '.craftdev' => array(
    'devMode' => false,
    'environmentVariables' => array(
      'fileSystemPath' => '/local/public_html/',
      'siteUrl' => "//www.example.craftdev"
    )
  ),
  '.com' => array(
    'cooldownDuration' => 0,
    'environmentVariables' => array(
      'fileSystemPath' => '/remote/public_html/',
      'siteUrl' => "//www.example.com"
     )
  )
);
```

I'm still having the issue. Not sure what's up.

**Comment by phaetons** [comment]
siteUrl is an array expecting language codes
'siteUrl' => array(
    'en' => 'http://example.com/',
    'de' => 'http://example.de/'
),

**Comment by pixeljitsu** [comment]
Thanks for the help,  I'm still having the issue.  Here is my general.php:

```
return array(
  '*' => array(
    'cpTrigger' => 'secret',
    'devMode' => false,
    'omitScriptNameInUrls' => true
  ),
  '.craftdev' => array(
    'devMode' => true,
    'environmentVariables' => array(
      'fileSystemPath' => '/local/public_html/',
      'siteUrl' => array(
        'en' => 'http://www.example.craftdev/'
      )
    )
  ),
  '.com' => array(
    'cooldownDuration' => 0,
    'environmentVariables' => array(
      'fileSystemPath' => '/remote/public_html/',
      'siteUrl' => array(
        'en' => 'http://www.example.com/'
      )
    )
  )
);
```
Setting the siteUrl to an array as you suggested causes a cascade of errors.

```
Array to string conversion :
[snip]/craft/app/services/ConfigService.php(681)
```
Here is the first part of the stack trace:

– [snip]/craft/app/services/ConfigService.php(681): str_replace("{siteUrl}", array("en" => "http://www.example.craftdev/",  "{siteUrl}")
```
676      */
677     public function parseEnvironmentString($str)
678     {
679         foreach ($this->get('environmentVariables') as $key => $value)
680         {
681             $str = str_replace('{'.$key.'}', $value, $str);
682         }
683 
684         return $str;
685     }
686 
```

**Comment by hubertprein** [comment]
Move the siteUrl outside the environmentVariables. Place it at the same level as environmentVariables is.

**Comment by pixeljitsu** [comment]
OK, that gets rid of the errors, thanks!

Just a note, I still have {siteUrl}http://example.com until I delete and then renenter all of the menus manually, but in this case that's not an issue at all.

Thanks again.

**Comment by hubertprein** [comment]
That's correct.

AmNav stores all URL's in a separate table. When Craft loads a whole bunch of elements with the ElementCriteriaModel, the PHP memory gets overloaded fast if you want more than X elements. By standard, Craft will get 100 elements. If you fetch more, you'll notice the performance will drop drastically. We've had projects that had a huge navigation that went 3 to 4 levels deep, and would fetch a lot of entries. This is why AmNav is not an Element Type and all the URLs are stored in a separate table, because of the performance. Through events (saving / deleting an entry) AmNav will update the URLs in the navigation that should be updated.

Just some information along the sideline, but good to hear your problem has been solved! Closing this issue.

**Comment by pixeljitsu** [comment]
FYI: Resaving the entry from the modal does not seem to update the uri at all.  If I move a page in a structure or change a slug, I have to actually delete the menu item and then add it back for the uri to change to the new location.
