### ISSUE TITLE
Need a page.first conditional

### ISSUE THREAD

**Issue by pixeljitsu** [am-impact/amnav#21]
It would be awesome if there were a way to conditionally use ```page.first``` with ```craft.amNav.getNavRaw``` as with ```page.active``` :
```
{% if page.active %}class="active"{% endif %}
```
Like this:
```
{% if page.first %}class="first"{% endif %}
```

I have a situation where top level dropdowns must have javascript:void(0) hrefs and there does not seem to be a way to assign the top level as being the active branch.  If were able to use page.first then I could assign the active styles to that class and bypass not being able to tell if the menu is active based on the URL location.

```
{% if page.hasActiveChild %}class="active"{% endif %}
```

Would be even better for complex menus.

**Comment by hubertprein** [comment]
While using the recursive macro, use Twig's loop.first to indicate if the node is the first in that level. The proper nodes will be active, based on the current URL.

In your scenario with hasActiveChild, am I correct when I say that one would create a navigation that would have a certain level with a different URI than it's children? If so, I can see why this could be useful in some scenarios.

**Comment by pixeljitsu** [comment]
Thanks for the direction.  I'll try loop.first, I should have thought of that myself.

I can see where hasActiveChild would be needed for children with different URIs.  It is not uncommon for clients to shift the menus about once the "committee" has had their hands in the sitemap.  hasActiveChild would solve some of that last minute coding.  :)

**Comment by pixeljitsu** [comment]
So if I create a menu item using my own URL, being '#' or 'javascript:void(0)', then how would loop.first know that the menu has active children?  

I have  a case now, where the client does not want any of the top level menu items with children to do anything other than hover for the dropdowns.   I can see no way to make the make the top level menu with a href of '#' or 'javascript:void(0)' active when one of its children are active.

Perhaps you could consider adding a new "placeholder" menu type that would output '#' or 'javascript:void(0)' in the href and would also register as active if any of its children we active, regardless of the URL structure.

**Comment by hubertprein** [comment]
Added in the latest release. See release notes for more info.
