### ISSUE TITLE
A&M adds the domain double to the nav

### ISSUE THREAD

**Issue by robbiepost** [am-impact/amnav#23]
When using A&M (version 1.4.2 ) in its standard config with Craft (version 2.3.2641) the domain is links are doubled in the URL.

`					{# A&M NAV PLUGIN NAVIGATION #}
					<nav class="header-col main-nav">
						<a href="#" class="nav-toggle"></a>
						{{ craft.amNav.getNav("mainNavigation") }}
					</nav>
`

This is what I would expect for a link to the entry "page": http://www.domain.com/page.html
and this is what the plugin renders after clicking the link: http://www.domain.com/http://www.domain.com/page.html

**Comment by hubertprein** [comment]
Fixed in latest release. 7d0589c768d1c9845db083700ad749fc8df23c0c
