### ISSUE TITLE
Ability to update node URLs after adding them.

### ISSUE THREAD

**Issue by dgrebb** [am-impact/amnav#24]
I built a nav and it worked great, then I changed the URI structure for my sections, and their entries now have different URIs. It would be fantastic if we could update the nav based on how an entry builds its URI after the fact.

Another side effect of this, double clicking a node, the entry shows the correct (updated) URI. Saving that node, the URL is not updated within the `url` column in `craft_amnav_nodes`.

Please reach out with any questions. The latest update and new UI are fantastic!

**Comment by dgrebb** [comment]
If anyone else has this problem, a simple query can be run to update your URLs:

`update craft_amnav_nodes set url = replace(url, '{siteUrl}path/to/content', '{siteUrl}content/to/path')`

**Comment by hubertprein** [comment]
@dgrebb Thanks for bringing this to my attention. I'll get back to this with a proper fix.

P.S. It's nice to hear that the latest (UI) update has been well received.

**Comment by hubertprein** [comment]
Fixed in the latest release.
