### ISSUE TITLE
Own Urls are not displayed.

### ISSUE THREAD

**Issue by emcacace** [am-impact/amnav#25]
I've created a navigation and added my own url but when I try to use it, it is not being displayed. I have used both craft.amNav.getNavRaw() and craft.amNav.getNav() but in neither case the own url shows up. Everything else works fine. 

On the admin side, I can see the node and edit it. I'm on 1.5.1 version.

**Comment by alexbrindalsl** [comment]
This appears to be an issue with the latest version - the additions of categories seems to have broken the own urls - I can confirm the issue.

I've reverted back to 1.4.2

**Comment by hubertprein** [comment]
Thanks for bringing this to my attention! It has been fixed in the latest release.
