### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by boboldehampsink** [am-impact/amnav#26]
You can add composer support by adding a composer.json with the following contents:

	{
	    "name": "am-impact/amnav",
	    "description": "Navigation Plugin for Craft",
	    "authors": [
	        {
	            "name": "Hubert Prein",
	            "email": "h.prein@am-impact.nl"
	        }
	    ],
	    "type": "craft-plugin",
	    "require": {
	        "composer/installers": "~1.0"
	    }
	}

Then you can submit your repo to Packagist. GitHub offers automatic packagist updating when you release a new version.

**Comment by hubertprein** [comment]
Thanks for the tip Bob! Added in the latest release.
