### ISSUE TITLE
Variable "menus" does not exist

### ISSUE THREAD

**Issue by mccombs** [am-impact/amnav#30]
Upon brand new install. I received this error.

/Applications/MAMP/htdocs/cota2/craft/plugins/amnav/templates/_index.twig(17)
`
17     <div id="nonavigations"{% if navigations %} class="hidden"{% endif %}>
18         <p>{{ 'There are no navigations yet.'|t }}</p>
19     </div>
`

**Comment by mccombs** [comment]
I cleared my template cache but it looks like migrating from an earlier version, say 1.2 to like 1.5 is not really an option. :(

**Comment by hubertprein** [comment]
Old migration bug. Fixed in latest release.
