### ISSUE TITLE
Migrations failing

### ISSUE THREAD

**Issue by dgrebb** [am-impact/amnav#36]
Howdy,

I went to updated to 1.6.3 from 1.4.2 and received this error in the log:

`2015/05/26 16:35:08 [error] [application] Failed to apply migration: m150403_093000_AmNav_nodesWithElements (time: 0.003s)`
`2015/05/26 16:35:08 [error] [application] Migration failed for plugin AmNav. All later AmNav migrations are canceled.`

Any ideas?

Best,
Dan

**Comment by hubertprein** [comment]
@dgrebb Hi Dan, the migration bug that I made between release 1.2 and 1.4 has really been haunting me! It's fixed in the latest release.

Best,
Hubert
