### ISSUE TITLE
Nav path active highlighting

### ISSUE THREAD

**Issue by johnwbaxter** [am-impact/amnav#37]
I've built a menu with two levels of nav. One of them is Knowledge Base -> Blog. When on blog, both levels are marked as active, but when you click on a blog post (not in the menu) that active highlighting is missing. Any idea on how i can retain the active path in the menu in this scenario?

I'm using just the a&m tag to output the markup, i tried customising it, but i couldn't get the custom markup to work the same as the output from the tag alone.

Thanks!

John

**Comment by hubertprein** [comment]
Should work just fine, as long as your URIs are correct. If your blog post section, doesn't match your overview / index page of your blog, it won't be highlighted as active.

Could you check this for me?

**Comment by johnwbaxter** [comment]
Uri path is correct blog overview is /blog and blog url is /blog/my-blog-post.

A puzzler!

**Comment by johnwbaxter** [comment]
Do you have any idea what i might be missing here? Are there any parameters i would need to set?

**Comment by johnwbaxter** [comment]
Ah! I downloaded your latest version and it's all working as expected now! Thanks!!

**Comment by hubertprein** [comment]
I'm glad it all worked out :)

**Comment by johnwbaxter** [comment]
Hey Hubert,

It's a superb plugin btw. Hugely impressed with it! Tried out the fieldtype yesterday too which is equally as awesome :)

Thanks

John

**Comment by hubertprein** [comment]
Hi John,

Thanks! Good to hear the plugin is to your liking :)
