### ISSUE TITLE
"New order saved" after saving nav

### ISSUE THREAD

**Issue by jayelkaake** [am-impact/amnav#40]
In /craft/plugins/amnav/resources/js/AmNav.js
Line 481 is hardcoded to always say "New order saved" after any save of the navigation menu. This should probably be changed to "Navigation saved".

**Comment by hubertprein** [comment]
Very late reply, but when I saw this I was already thinking that the messages that are currently displayed are decent enough for everyone to understand what is happening :)

Closing this.
