### ISSUE TITLE
Sample template code to generate same html as just using the tag

### ISSUE THREAD

**Issue by johnwbaxter** [am-impact/amnav#42]
Hey Guys,

Would it be possible to amend the sample code, or add new! that matches the output that just using the tag would generate? The tag alone almost outputs the html i need, but not quite. I have tried using the tags to output my own html, but i can't seem to get the html to output in the same way as just using the tag.

I hope that makes sense!

Thanks

John

**Comment by hubertprein** [comment]
Sorry for the late reply.

Please see the updated readme.

**Comment by johnwbaxter** [comment]
No worries, massively appreciate you doing that for me!! Thanks very much!!
