### ISSUE TITLE
active class not being added

### ISSUE THREAD

**Issue by middle8media** [am-impact/amnav#45]
This may be similar to #37 or #19 

the active state is not being added. I am using relative urls in the plugin fields

![screen shot on 2015-08-19 at 10-22-02](https://cloud.githubusercontent.com/assets/1033332/9358867/38f57dde-465c-11e5-9bef-4ee721cac89e.png)

**Comment by middle8media** [comment]
I am using relative urls because as I deep dive into blog posts/categories/authors etc... the relative url path for `/about` is need to return to the about page.

**Comment by middle8media** [comment]
here is my blog path

/blog
/blog/2015/08/10/mapping-community-resilience-in-indonesia-video

**Comment by middle8media** [comment]
Any thoughts on this? Thanks.

**Comment by hubertprein** [comment]
@middle8media Fixed in latest release.

**Comment by middle8media** [comment]
Thanks.
