### ISSUE TITLE
Level 1 in the header and level 2...3..4 in sidebar

### ISSUE THREAD

**Issue by worfoual** [am-impact/amnav#5]
I can display the level 1 of my menu in the header but I can't/don't know how to display the level 2, level 3... from the (active)level 1 in a sidebar.

In my header I have:
<ul>
{{ craft.amNav.getNav("mainMenu", {
maxLevel: '1',
classActive: 'active',
excludeUl: '1'	
}) }}
</ul>

How do I get the level 2, level 3 from (active)level 1 in a sidebar? In your parameters I see this one: startFromId but I think I should need something like this: startFromLevel.

Sorry for my poor english.
Francois

**Comment by WhirlyGuy** [comment]
@hubertprein Sorry for popping in on the end of this discussion like this but was just wondering how you go about using that getActivePageIdForLevel function in conjunction with the startFromId parameter?

A bit of a newb to Craft and the plugins so not too sure how you code this sort of thing? Didn't see it mentioned in the Docs either so a little confused as to exactly how to do that sort of thing as mentioned in the posts above.

Many thanks in advance for any help with this.
