### ISSUE TITLE
Template Error

### ISSUE THREAD

**Issue by dgrebb** [am-impact/amnav#54]
This was done on a dev environment after the Craft 2.5 beta came out. Steps taken:

1) Upgrade Craft to 2.5.2715
2) Upgrade amnav from 1.1.7 to 1.7.0
3) Navigate to http://craft.dev/admin/amnav
4) Template error:

```
Template Error

Variable "menus" does not exist

/Users/dgrebb/Projects/00 Sandbox/craftcms/craft/plugins/amnav/templates/_index.twig(17)

05 
06 {% if currentUser.admin or settings.canDoActions %}
07     {% set sidebar %}
08         <div class="buttons">
09             <a href="{{ url('amnav/new') }}"><div class="btn submit add icon">{{ 'New navigation'|t }}</div></a>
10         </div>
11     {% endset %}
12 {% endif %}
13 
14 {% set content %}
15     <h1>{{ 'Created navigations'|t }}</h1>
16 
17     <div id="nonavigations"{% if navigations %} class="hidden"{% endif %}>
```

Line 17 is the one in question. Any ideas?

**Comment by hubertprein** [comment]
AmNav doesn't seem to work properly with 2.5 at all at the moment. Your issue is something else I'd say, since line 17 doesn't correspond with the error you're receiving. Try to remove the template cache in the CP and see what happens :)

**Comment by dgrebb** [comment]
Thanks Hubert. That did it (and now I see the breaking :)

**Comment by hubertprein** [comment]
@dgrebb It's been updated for Craft 2.5 in the **dev** branch :)
