### ISSUE TITLE
How Can I display Parent of a specific Node?

### ISSUE THREAD

**Issue by bgarrant** [am-impact/amnav#56]
I am trying to display a node and it's parent and I can't figure it out.  Here is my code:

```
			<h3>I NEED TO GET THE PARENT NODE TITLE HERE</h3>
				{{ craft.amNav.getNav("mainNavigation", {
    			id: 'subnav',
    			startFromId: 2,
    			maxLevel: 1
			}) }}
```

What am I doing wrong?

**Comment by bgarrant** [comment]
Anyone know how to do this?  I just need the Title of the parent node.

**Comment by brettdewoody** [comment]
Try starting from the parent node.

**Comment by bgarrant** [comment]
startFromId: 2 is the top level node.  I just can't get it to display the parent node name, which in this case node 2 is "About".  Any idea what I am missing?

**Comment by Jammooka** [comment]
Seeing as you know the id of the entry, just call it directly:

`{{ craft.entries.id(2).first().title }}`

**Comment by hubertprein** [comment]
I recon you figured it out.

If you need more help with this, please reopen the issue.
