### ISSUE TITLE
The modal window's styles are broken upon adding successive entries

### ISSUE THREAD

**Issue by jsunsawyer** [am-impact/amnav#57]
![screen shot 2015-11-30 at 11 22 21 am](https://cloud.githubusercontent.com/assets/1007191/11481965/160965ca-9755-11e5-8cab-069b7ab34a70.png)

Tested running latest Chrome and and Firefox on Mac

**Comment by hubertprein** [comment]
Did you update to the latest craft and amnav release?

**Comment by jsunsawyer** [comment]
Yes. Latest craft and amnav is installed.

First time I go to add an entry:
![screen shot 2015-12-04 at 8 48 53 am](https://cloud.githubusercontent.com/assets/1007191/11595360/e7d4c2c8-9a63-11e5-9198-ab0f3a528ff9.png)

Upon adding a 2nd entry:
![screen shot 2015-12-04 at 8 48 28 am](https://cloud.githubusercontent.com/assets/1007191/11595364/f17b53aa-9a63-11e5-82d7-618b1620b5c3.png)

**Comment by dustinwalker** [comment]
I am also seeing the same issue on version 1.7.1 and Craft 2.5.2750. It looks like there is a class of "collapsed" being added to that table on subsequent modal loads in the same sequence as described above.

![sample](https://cloud.githubusercontent.com/assets/360177/11662459/528a0b56-9d9c-11e5-98c9-c3df25554baf.png)

**Comment by hubertprein** [comment]
@dustinwalker As far as I know, this is Craft's part. I simply hook into Craft's JS capabilities.
