### ISSUE TITLE
Feature request: option for icons in lieu or edition to text

### ISSUE THREAD

**Issue by stubear** [am-impact/amnav#60]
It would be nice to have the ability to use svg or png icons in addition to or in lieu of navigation text. I see this as four new fields in the Entries, Categories, and My Own URL panels; an asset field for the icon, a switch for remove text, and width/height fields. The text would still be used but if remove text was switched on the text would be placed in the image alt attribute.

**Comment by hubertprein** [comment]
Not something we will be adding any time soon, because using assets will take some code to support all that in the navigation, but I can see why you want to do this.

Closing this for now.
