### ISSUE TITLE
Category Items not showing in Breadcrumbs

### ISSUE THREAD

**Issue by bgarrant** [am-impact/amnav#63]
Categories work great in main navigation but go not show up in breadcrumbs?  Any idea why?  I have a category page working and added to the nav but it is missing in the breadcrumbs.

**Comment by bgarrant** [comment]
Any update on this Breadcrumb issue?  Nav works fine.  SO here is a better example:

http://domain.dev/programs/adult-programs/senior-citizens-club is the entry URL.

http://domain.dev/programs/adult-programs/ is the Category page which is pulling {{ category.title }} and {{ category.body }} into the page and the segment two "adult-programs" is the slug it is using.  The template is at "/programs/_entry".

My breadcrumb code is:

`{{ craft.amNav.getBreadcrumbs({
	id: 'breadcrumbs',
	class: 'breadcrumb',
	renameHome: 'Home'
}) }}`

So when I visit http://domain.dev/programs/adult-programs/senior-citizens-club I get the breadcrumb "Home > Senior Citizens Club" when it should be "Home > Adult Programs > Senior Citizens Club".  Why is the category page being skipped in the breadcrumbs?

**Comment by hubertprein** [comment]
Ahh yes, categories are not in the breadcrumbs at all. Have to come up with an update for that one.

**Comment by bgarrant** [comment]
Please keep me posted. I would be happy to help test if needed. 

Bryan Garrant
Garrant Consulting LLC

**Comment by bgarrant** [comment]
They work great in the navigation. Just missing in breadcrumbs. Thanks in advance for your help. It is a wonderful plugin. :)

Bryan Garrant
Garrant Consulting LLC

**Comment by bgarrant** [comment]
Have you had a chance to look at this one Hubert?  Not a big deal but just wanted to follow up.  Thanks.

**Comment by dubcanada** [comment]
I fixed it in the following pull request @bgarrant  https://github.com/am-impact/amnav/pull/67

**Comment by bgarrant** [comment]
Fantastic.  I will test it out.

 

Bryan Garrant

Garrant Consulting LLC

518.327.5159

**Comment by bgarrant** [comment]
This works perfect!  Thanks so much.

 

Bryan Garrant

Garrant Consulting LLC

518.327.5159
