### ISSUE TITLE
"Class for list item" not available to non-admins

### ISSUE THREAD

**Issue by AdamChlan** [am-impact/amnav#65]
When clicking the edit link for a navigation element, and the modal appears, the "Class for list item" field/option does not appear for non-admins. Any thoughts on adding this in?

**Comment by hubertprein** [comment]
When building that feature, we had in mind that only admins should see this because we think that the regular clients shouldn't have access to the way a navigation is displayed. We think that the client shouldn't be the one adding classes to a node, but rather have their admins do it.

**Comment by codyjames** [comment]
We'd like non-admins to be able to edit the class as well. Navigation changes should be calculated and considered at all times. If you give non-admins the ability to edit a Navigation, why not give them access to all available options? If they can delete items entirely without an admin, they should be able to add/adjust a classes.
