### ISSUE TITLE
Relative vs Absolute URLs

### ISSUE THREAD

**Issue by nfourtythree** [am-impact/amnav#7]
Just a quick heads up. I have noticed an issue in respect to entering custom urls as to whether they should be input relatively or absolutely.

For example if I enter a custom item with the url "app/test" and output the nav on the /app page I will receive the url app/app/test. This is not a problem as I understand this gives flexibility however issues do arise when using things like the .active parameter.

So in my example I have now added the url as a full path "/app/test", so that there are no issues on sub pages but when the comparison happens to see if a url is active (AmNavService.php:_isPageActive:315) ```craft()->request->getPath()``` returns "app/test" and the code compares it to "/app/test" therefore no match found.

There are a few ways to get round this but just thought I would try and be helpful and bring it to your attention.

Keep up the good work!

**Comment by middle8media** [comment]
similar to #45?

**Comment by nfourtythree** [comment]
@middle8media This was a little while ago now, I believe I got round it by using the get raw and writing my own macro which stripped the first slash when testing against active

**Comment by middle8media** [comment]
@nfourtythree Thanks.
